# Provisioning
compartment_id: "ocid1.tenancy.oc1..aaaaaaaajzdeabpe55pastcezhhjrqxopgyhvnjeqhi6hvjhvbeip7rl5e2a"
web_network_name: "web server network"
sec_network_name: "secure network"
web_host_name: "web1"
docker_host_name: 'containers'
web_test_host_name: "web test server"
docker_test_host_name: "containers test server"
web_availability_domain: "wjxn:US-CHICAGO-1-AD-2"
sec_availability_domain: "wjxn:US-CHICAGO-1-AD-3"
image_id: "ocid1.image.oc1.us-chicago-1.aaaaaaaamuljpdngivodn4gtramvxgztbuykhurwaueqcaxs7audzzav74ba"
