- hosts: all:!localhost
  become: true
  vars:
    ansible_user: flowlogix
    oci_hostname_conf_name: "/etc/oci-hostname.conf"
    content_dir: "/var/flowlogix"
  tasks:
    - name: Check for OCI hostname file
      stat:
        path: "{{ oci_hostname_conf_name }}"
      register: oci_hostname_conf

    - name: Ensure OCI doesn't clobber the hostname
      lineinfile:
        path: "{{ oci_hostname_conf_name }}"
        regexp: '^PRESERVE_HOSTINFO'
        line: 'PRESERVE_HOSTINFO=2'
      when: oci_hostname_conf.stat.exists

    - name: Set Hostname
      hostname:
        name: "{{ inventory_hostname_short }}"

    - name: Make Content and Config directories
      file:
        path: "{{ content_dir }}/etc/ssl/"
        owner: "{{ ansible_env.SUDO_USER }}"
        state: directory
      tags: ssl

    - name: Copy SSL certificates
      become: false
      failed_when: false
      synchronize:
        src: "~/var/ssl-links/"
        dest: "{{ content_dir }}/etc/ssl/"
        copy_links: true
        delete: true
      notify:
        - Reload Apache
        - Reload Docker
      tags: ssl
