- hosts: webservers
  become: yes
  vars:
    local_home: "{{ lookup('env', 'HOME') }}"
  tasks:
    - name: Create users and add to docker group
      user:
        name: "{{ item.name }}"
        groups:
          - docker
          - flowlogix
        append: yes
        state: present
      loop: "{{ users }}"

    - name: Create .ssh directory for users
      file:
        path: "~{{ item.name }}/.ssh"
        state: directory
        owner: "{{ item.name }}"
        mode: '0700'
      loop: "{{ users }}"

    - name: Add SSH public key for users
      authorized_key:
        user: "{{ item.name }}"
        state: present
        key: "{{ lookup('file', local_home + '/.ssh/' + item.ssh_keyname + '.pub') }}"
      loop: "{{ users }}"

    - name: Delete users
      user:
        name: "{{ item.name }}"
        state: absent
        remove: yes
        force: yes
      loop: "{{ users }}"
      tags: delete
      when: "'delete' in ansible_run_tags"
