- import_playbook: "{{ playbook_dir }}/configure-common.yaml"
- hosts: docker
  become: true
  vars:
    docker_base: https://download.docker.com/linux/centos
    os_version: 9

  tasks:
    - name: include vars
      include_vars: "{{ playbook_dir }}/config-vars.yaml"
      tags: always

    - name: Add docker repository
      yum_repository:
        name: docker_repo
        description: Docker Repository
        baseurl: "{{ docker_base }}/{{ os_version }}/{{ ansible_architecture }}/stable"

    - name: Verify Docker PGP keys
      rpm_key:
        key: "{{ docker_base }}/gpg"

    - name: Install docker engine
      package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        update_cache: yes
      notify:
        - Reload Docker

    - name: Create docker group
      group:
        name: docker
        gid: 900

    - name: Add user to docker group
      user:
        name: "{{ ansible_env.SUDO_USER }}"
        groups: docker
        append: true

    - name: Create docker systemd configuration directory
      file:
        dest: /etc/systemd/system/docker.service.d/
        state: directory
      tags: docker_config

    - name: Create docker configuration directory
      file:
        dest: /etc/docker
        state: directory
      tags: docker_config

    - name: Configure Docker (systemd)
      copy:
        dest: /etc/systemd/system/docker.service.d/override.conf
        content: |
          [Service]
          ExecStart=
          ExecStart=/usr/bin/dockerd -H fd://
          ExecStartPost=/usr/bin/docker run --privileged --rm tonistiigi/binfmt --install all
      notify:
        - Reload systemd
        - Reload Docker
      tags: docker_config

    - name: Configure Docker (json)
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "experimental": true,
            "features": {
              "containerd-snapshotter": true
            },
            "registry-mirrors": [
              "https://registry-1.docker.io"
            ]
          }
      notify:
        - Reload systemd
        - Reload Docker
      tags: docker_config

    - name: Enable and Start Docker engine
      service:
        name: 'docker'
        enabled: true
        state: started

    - name: Create Jenkins directories
      file:
        dest: var/jenkins
        state: directory
      become: false

  handlers:
    - name: Reload systemd
      systemd_service:
        daemon_reload: true

    - name: Reload Docker
      service:
        name: 'docker'
        state: restarted
