- import_playbook: "{{ playbook_dir }}/configure-common.yaml"
- hosts: docker
  become: true
  vars:
    ansible_user: flowlogix
    docker_base: https://download.docker.com/linux/centos
    os_version: 9
  tasks:
    - name: Add docker repository
      yum_repository:
        name: docker_repo
        description: Docker Repository
        baseurl: "{{ docker_base }}/{{ os_version }}/{{ ansible_architecture }}/stable"

    - name: Verify PGP keys
      rpm_key:
        key: "{{ docker_base }}/gpg"

    - name: Install docker engine
      package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        update_cache: yes
      notify:
        - Reload Docker

    - name: Add docker group
      user:
        name: "{{ ansible_env.SUDO_USER }}"
        groups: docker
        append: true

    - name: Create docker configuration directory
      file:
        dest: /etc/systemd/system/docker.service.d/
        state: absent
      notify:
        - Reload systemd
        - Reload Docker
      tags: docker_config

    - name: Enable and Start Docker engine
      service:
        name: 'docker'
        enabled: true
        state: started

  handlers:
    - name: Reload systemd
      systemd_service:
        daemon_reload: true

    - name: Reload Docker
      service:
        name: 'docker'
        state: restarted
