- hosts: linux_hosts
  become: true
  tasks:
    - name: Install Apache Web Server
      package:
        name: 'httpd'
        state: latest
        update_cache: yes

    - name: Enable and Start Apache Web Server
      service:
        name: 'httpd.service'
        enabled: true
        state: started

    - name: Open http(s) ports (firewall)
      firewalld:
        port: "{{ item }}/tcp"
        state: enabled
        immediate: true
        permanent: true
      loop:
        - 80
        - 443

    - name: make content directory
      file:
        path: /var/flowlogix
        owner: "{{ ansible_env.SUDO_USER }}"
        state: directory

    - name: Enable SeLinux content directory
      command: semanage fcontext -a -t httpd_sys_content_t "/var/flowlogix(/.*)?"
      changed_when: false
      failed_when: false
      no_log: true
      register: selinux

    - name: display selinux stuff
      debug:
        msg: "stdout: {{ selinux.stdout }} stderr: {{ selinux.stderr }}"

    - name: Enable own Apache config
      blockinfile:
        path: /etc/httpd/conf.d/flowlogix.conf
        block: |
          IncludeOptional /var/flowlogix/etc/httpd/conf.d/*
        create: true
      notify: Reload Apache

  handlers:
    - name: Reload Apache
      service:
        name: "httpd.service"
        state: reloaded
