- import_playbook: "{{ playbook_dir }}/common/configure-common.yaml"
- name: Install and configure WireGuard
  hosts: webservers
  become: true
  tasks:
    - name: Install WireGuard
      package:
        name:
          - wireguard-tools
          - iptables
        state: latest

    - name: Enable IP forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: true
        state: present
        reload: true

    - name: Create WireGuard configuration directory
      file:
        path: /etc/wireguard
        state: directory
        mode: '0700'

    - name: Generate WireGuard private key (wg genkey) and Pre-shared key (wg genpsk)
      shell: wg genkey
      register: wg_private_key
      when: server_private_key is undefined or server_private_key == ""
      no_log: true

    - name: Generate WireGuard public key
      shell: echo "{{ server_private_key | default(wg_private_key.stdout) }} " | wg pubkey
      register: wg_public_key
      no_log: true
      changed_when: false

    - name: Create WireGuard configuration file
      copy:
        content: |
          [Interface]
          Address = {{ item.value.address }}
          PrivateKey = {{ item.value.private_key if item.value.private_key != '' else wg_private_key.stdout }}
          {% if item.value.server is defined and item.value.server %}
          ListenPort = {{ item.value.port }}
          PreUp = iptables -t mangle -A PREROUTING -i {{ item.key }} -j MARK --set-mark 0x30
          PreUp = iptables -t nat -A POSTROUTING ! -o {{ item.key }} -m mark --mark 0x30 -j MASQUERADE
          PostDown = iptables -t mangle -D PREROUTING -i {{ item.key }} -j MARK --set-mark 0x30
          PostDown = iptables -t nat -D POSTROUTING ! -o {{ item.key }} -m mark --mark 0x30 -j MASQUERADE
          {% endif %}

          {% for peer in item.value.peers %}
          [Peer]
          PublicKey = {{ peer.public_key }}
          AllowedIPs = {{ peer.allowed_ips }}
          {% if peer.preshared_key is defined and peer.preshared_key != '' %}
          PresharedKey = {{ peer.preshared_key }}
          {% endif %}
          {% if peer.endpoint is defined %}
          Endpoint = {{ peer.endpoint }}
          {% endif %}
          {% if peer.persistent_keepalive is defined %}
          PersistentKeepalive = {{ peer.persistent_keepalive }}
          {% endif %}

          {% endfor %}
        dest: "/etc/wireguard/{{ item.key }}.conf"
        mode: '0600'
      no_log: true
      loop: "{{ wireguard_interfaces | dict2items }}"
      notify: restart wireguard

    - name: Enable and start WireGuard service
      service:
        name: "wg-quick@{{ item.key }}"
        enabled: true
        state: started
      no_log: true
      loop: "{{ wireguard_interfaces | dict2items }}"

    - name: Display WireGuard public key
      debug:
        msg: "Public Key: {{ wg_public_key.stdout }}"
      when: wg_public_key.stdout is defined

  handlers:
    - name: restart wireguard
      service:
        name: "wg-quick@{{ item.key }}"
        state: restarted
      no_log: true
      loop: "{{ wireguard_interfaces | dict2items }}"
