- import_playbook: "{{ playbook_dir }}/common/configure-common.yaml"

### HAProxy Setup
- hosts: docker
  become: true
  tasks:
    - name: Install HAProxy, rsync zsh and socat
      package:
        name:
          - haproxy
          - socat
          - zsh
          - policycoreutils-python-utils
          - rsync
        state: latest
        update_cache: yes
      notify:
        - Reload haproxy
      tags: install

    - name: Copy SSL certificates
      become: true
      failed_when: false
      synchronize:
        src: "~/var/ssl-links/"
        dest: "/etc/ssl/certs/flowlogix/"
        owner: false
        group: false
        copy_links: true
        delete: true
        rsync_opts:
          - "--chown=root:haproxy"
          - "--chmod=g+rX"
      tags: ssl

    - name: Find valid infra base path
      set_fact:
        infra_base: "{{ lookup('first_found', ['~/dev/infra', '~/infra'], errors='ignore') }}"
      tags: always

    - name: Copy Haproxy Configurations
      become: true
      failed_when: false
      synchronize:
        src: "{{ infra_base }}{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: false
        group: false
        checksum: true
        times: false
        delete: true
      loop:
        - { src: "/etc/haproxy-cloud.cfg", dest: "/etc/haproxy/" }
        - { src: "/etc/haproxy/", dest: "/etc/haproxy/conf.d/" }
        - { src: "/scripts/ssl/haproxy-update-certs.sh", dest: "/usr/local/bin/" }
      notify: Reload haproxy
      tags:
        - config
        - haproxy

    - name: Set Haproxy Options (systemd)
      copy:
        dest: /etc/sysconfig/haproxy
        content: |
          CONFIG=/etc/haproxy/haproxy-cloud.cfg
      notify: Reload haproxy
      tags: config

    - name: Create HAProxy systemd override directory
      become: true
      file:
        path: /etc/systemd/system/haproxy.service.d
        state: directory
        mode: "0755"
      tags: config

    - name: Allow haproxy to bind to low ports
      become: true
      copy:
        dest: /etc/systemd/system/haproxy.service.d/override.conf
        content: |
          [Service]
          AmbientCapabilities=CAP_NET_BIND_SERVICE
          Environment=OPTIONS=
      notify:
        - Reload haproxy
      tags: config

    - name: Allow binding on ports 9999 and 18080 in SELinux
      become: true
      command: "semanage port -a -t http_port_t -p tcp {{ item }}"
      loop:
        - 9999
        - 18080
      changed_when: false
      tags: config

    - name: Allow HAProxy network connectivity
      become: true
      seboolean:
        name: haproxy_connect_any
        state: yes
        persistent: yes
      tags: config

    - name: Enable and Start Haproxy Service
      service:
        name: 'haproxy.service'
        enabled: true
        state: started

  handlers:
    - name: Reload haproxy
      service:
        name: "haproxy.service"
        state: reloaded

### Web Server Setup

- hosts: webservers
  become: true
  vars:
    content_dir: "/var/flowlogix"
    etc_conf_d: "{{ content_dir }}/etc/httpd/conf.d"
    os_etc_conf_d: "/etc/httpd/conf.d"
  tasks:
    - name: Install Apache Web Server
      package:
        name:
          - httpd
        state: latest
        update_cache: yes
      notify:
        - Reload Apache
      tags: install

    - name: Enable SeLinux content directory
      command: semanage fcontext -a -t httpd_sys_content_t "{{ content_dir }}(/.*)?"
      changed_when: false
      failed_when: false
      no_log: true
      register: selinux
      tags: config

    - name: Make Content and Config directories
      file:
        path: "{{ item }}"
        owner: "{{ ansible_facts.env.SUDO_USER }}"
        state: directory
      loop:
        - "{{ etc_conf_d }}"
        - "{{ content_dir }}/html"
        - "{{ content_dir }}/downloads"
      tags: config

    - name: Change Apache Listen port from 8080 to 18080
      lineinfile:
        path: "{{ os_etc_conf_d }}/../conf/httpd.conf"
        regexp: '^Listen\s+80'
        line: 'Listen 18080'
        backup: yes
      notify: Reload Apache
      tags: config

    - name: Enable own Apache config
      blockinfile:
        path: "{{ os_etc_conf_d }}/flowlogix.conf"
        block: |
          IncludeOptional "{{ etc_conf_d }}/*"
        create: true
      notify: Reload Apache
      tags: config

    - name: Write apache config for docroot
      blockinfile:
        path: "{{ os_etc_conf_d }}/docroot.conf"
        block: |
          DocumentRoot "{{ content_dir }}/html"
          <Directory "{{ content_dir }}/html">
              Options Indexes FollowSymLinks
              AllowOverride All
              Require all granted
          </Directory>
          <Directory "{{ content_dir }}/downloads">
              AllowOverride None
              Require all granted
          </Directory>
        create: true
      notify: Reload Apache
      tags: config

    - name: Copy Apache Config
      become: false
      failed_when: false
      synchronize:
        src: "{{ infra_base }}/etc/httpd/"
        dest: "{{ content_dir }}/etc/httpd/"
        copy_links: true
        checksum: true
        times: false
        delete: true
      notify: Reload Apache
      tags: config

    - name: SeLinux fix file permissions
      command: restorecon -Rv "{{ content_dir }}"
      changed_when: false
      tags: config

    - name: Set Apache Options (systemd)
      copy:
        dest: /etc/systemd/system/httpd.service.d/override.conf
        content: |
          [Service]
          Environment=OPTIONS=
      notify: Reload Apache
      tags: config

    - name: Enable and Start Apache Web Server
      service:
        name: 'httpd.service'
        enabled: true
        state: started

  handlers:
    - name: Reload Apache
      service:
        name: "httpd.service"
        state: reloaded
