- hosts: linux_hosts
  become: true
  vars:
    content_dir: "/var/flowlogix"
    etc_conf_d: "{{ content_dir }}/etc/httpd/conf.d"
    os_etc_conf_d: "/etc/httpd/conf.d"
    oci_hostname_conf_name: "/etc/oci-hostname.conf"
  tasks:
    - name: Check for OCI hostname file
      stat:
        path: "{{ oci_hostname_conf_name }}"
      register: oci_hostname_conf

    - name: Ensure OCI doesn't clobber the hostname
      lineinfile:
        path: "{{ oci_hostname_conf_name }}"
        regexp: '^PRESERVE_HOSTINFO'
        line: 'PRESERVE_HOSTINFO=2'
      when: oci_hostname_conf.stat.exists

    - name: Set Hostname
      hostname:
        name: "{{ inventory_hostname_short }}"

    - name: Install Apache Web Server
      package:
        name: 'httpd'
        state: latest
        update_cache: yes
      notify: Reload Apache

    - name: Install Apache Mod_SSL
      package:
        name: 'mod_ssl'
        state: latest
        update_cache: yes
      notify: Reload Apache

    - name: Open http(s) ports (firewall)
      firewalld:
        port: "{{ item }}/tcp"
        state: enabled
        immediate: true
        permanent: true
      loop:
        - 80
        - 443

    - name: Enable SeLinux content directory
      command: semanage fcontext -a -t httpd_sys_content_t "{{ content_dir }}(/.*)?"
      changed_when: false
      failed_when: false
      no_log: true
      register: selinux

    - name: Make Content and Config directories
      file:
        path: "{{ item }}"
        owner: "{{ ansible_env.SUDO_USER }}"
        state: directory
      loop:
        - "{{ etc_conf_d }}"
        - "{{ content_dir }}/html"

    - name: Enable own Apache config
      blockinfile:
        path: "{{ os_etc_conf_d }}/flowlogix.conf"
        block: |
          IncludeOptional "{{ etc_conf_d }}/*"
        create: true
      notify: Reload Apache

    - name: Write apache config for docroot
      blockinfile:
        path: "{{ os_etc_conf_d }}/docroot.conf"
        block: |
          DocumentRoot "{{ content_dir }}/html"
          <Directory "{{ content_dir }}/html">
              Options Indexes FollowSymLinks
              AllowOverride All
              Require all granted
          </Directory>
        create: true
      notify: Reload Apache

    - name: Disable self-signed certificates
      lineinfile:
        dest: "{{ os_etc_conf_d }}/ssl.conf"
        regexp: "(?i)^({{ item }}.*)"
        line: '# Disabled by FlowLogix --- \1'
        backrefs: yes
      notify: Reload Apache
      loop:
        - SSLCertificateFile
        - SSLCertificateKeyFile

    - name: Copy SSL certificates
      become: false
      failed_when: false
      synchronize:
        src: "~/var/ssl-links/"
        dest: "{{ content_dir }}/etc/ssl/"
        copy_links: true
        delete: true
      notify: Reload Apache
      tags: ssl

    - name: Copy Apache Config
      become: false
      failed_when: false
      synchronize:
        src: "{{ item }}/etc/httpd/"
        dest: "{{ content_dir }}/etc/httpd/"
        copy_links: true
        checksum: true
        times: false
        delete: true
      loop:
        - "~/infra"
        - "~/dev/infra"
      notify: Reload Apache
      tags: config

    - name: SeLinux fix file permissions
      command: restorecon -Rv "{{ content_dir }}"
      changed_when: false

    - name: Enable and Start Apache Web Server
      service:
        name: 'httpd.service'
        enabled: true
        state: started

  handlers:
    - name: Reload Apache
      service:
        name: "httpd.service"
        state: reloaded
