- hosts: localhost
  gather_facts: false
  collections:
    - oracle.oci
  tasks:
  - name: include vars
    include_vars: "{{ playbook_dir }}/common/config-vars.yaml"

  - name: Look up Test Server(s)
    oci_compute_instance:
      name: "{{ lookup('vars', item + '_host_name') }}"
      compartment_id: "{{ compartment_id }}"
    check_mode: true
    changed_when: false
    register: servers
    loop:
      - web_test
      - docker_test

  - name: Remove Test Server(s)
    oci_compute_instance:
      id: "{{ item.instance.id }}"
      compartment_id: "{{ compartment_id }}"
      state: absent
    when: item.instance.id is defined
    no_log: true
    loop:
      "{{ servers.results }}"
