- hosts: localhost
  gather_facts: false
  collections:
    - oracle.oci
  tasks:
  - name: include vars
    include_vars: "{{ playbook_dir }}/common/config-vars.yaml"
    tags:
    - always

  - name: Look up Test Server(s)
    oci_compute_instance:
      name: "{{ lookup('vars', item + '_host_name') }}"
      compartment_id: "{{ compartment_id }}"
    check_mode: true
    changed_when: false
    register: servers
    loop:
      - web_test
      - docker_test

  - name: Remove Test Server(s)
    oci_compute_instance:
      id: "{{ item.instance.id }}"
      compartment_id: "{{ compartment_id }}"
      state: absent
    when: item.instance.id is defined
    no_log: true
    loop:
      "{{ servers.results }}"

  - name: Remove Longhorn backup bucket
    oci_object_storage_bucket:
      namespace_name: "{{ bucket_namespace }}"
      compartment_id: "{{ compartment_id }}"
      name: 'longhorn-backups'
      force: yes
      state: 'absent'
    tags:
      - storage
      - never
