- hosts: linux_hosts
  become: true
  tasks:
    - name: Upgrade OS
      package:
        name: '*'
        state: latest
        update_cache: yes

    - name: Check if reboot is required
      shell:
        cmd: "needs-restarting -r"
      changed_when: false
      failed_when: reboot_required.rc != 0 and reboot_required.rc != 1
      check_mode: false
      register: reboot_required

    - name: Reboot if required
      reboot:
      when: reboot_required.rc == 1
