- hosts: test1.oci.flowlogix.com
  tasks:
    - name: Upgrade OS
      ansible.builtin.package:
        update_cache: yes

    - name: Check if reboot required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot if required
      reboot:
      when: reboot_required_file.stat.exists == true
