- hosts: linux_hosts
  tasks:
    - name: Upgrade OS
      become: true
      ansible.builtin.package:
        update_cache: yes

    - name: Check if reboot required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot if required
      become: true
      reboot:
      when: reboot_required_file.stat.exists == true
