apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
networking:
  podSubnet: 192.168.0.0/16
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
nodeRegistration:
  criSocket: unix:///var/run/cri-dockerd.sock
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
serverTLSBootstrap: true
failSwapOn: false
systemReserved:
  memory: 300Mi
kubeReserved:
  memory: 800Mi
featureGates:
  NodeSwap: true
memorySwap:
  swapBehavior: LimitedSwap
