apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
nodeRegistration:
  criSocket: unix:///var/run/cri-dockerd.sock
discovery:
  bootstrapToken:
    apiServerEndpoint: {{ controller_address }}:6443
    token: {{ join_token }}
    caCertHashes:
      - {{ cert_hash }}
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
failSwapOn: false
systemReserved:
  memory: 300Mi
kubeReserved:
  memory: 400Mi
featureGates:
  NodeSwap: true
memorySwap:
  swapBehavior: LimitedSwap
