apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payara
  name: payara
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payara
  template:
    metadata:
      labels:
        app: payara
    spec:
      containers:
      - image: lprimak/payara-full
        name: server-full
        env:
          - name: RMI_SERVER_HOSTNAME
            value: payara.local.hope.nyc.ny.us
        resources:
          requests:
            memory: "1Gi"
          limits:
            memory: "1.5Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: payara
  annotations:
#    metallb.universe.tf/loadBalancerIPs: 10.0.62.3
spec:
  type: LoadBalancer
  selector:
    app: payara
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080
    - protocol: TCP
      name: https
      port: 443
      targetPort: 8181
    - protocol: TCP
      name: admin
      port: 4848
      targetPort: 4848
    - protocol: TCP
      name: debug
      port: 9009
      targetPort: 9009
    - protocol: TCP
      name: jmx-rmi
      port: 9010
      targetPort: 9010
    - protocol: TCP
      name: jmx-payara
      port: 8686
      targetPort: 8686
