apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payara
  name: payara
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payara
  template:
    metadata:
      labels:
        app: payara
    spec:
      containers:
      - image: lprimak/payara-full
        name: server-full
        env:
          - name: MAX_HEAP_SIZE
            value: 725m
          - name: PAYARA_JVM_OPTIONS
            value: "-XX:+UseZGC"
          - name: RMI_SERVER_HOSTNAME
            value: payara.svc
          - name: PAYARA_ARGS
            value: "--postbootcommandfile /home/flowlogix/var/payara-applications/deploy.txt"
        resources:
          requests:
            memory: "1Gi"
          limits:
            memory: "4.5Gi"
        volumeMounts:
        - name: payara-applications
          mountPath: /home/flowlogix/var/payara-applications
          readOnly: true
          recursiveReadOnly: IfPossible
      volumes:
      - name: payara-applications
        persistentVolumeClaim:
          claimName: payara-applications
          readOnly: true
      securityContext:
        fsGroup: 1000
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: "memory-sensitive"
                operator: DoesNotExist
---
apiVersion: v1
kind: Service
metadata:
  name: payara
  annotations:
#    metallb.universe.tf/loadBalancerIPs: 10.0.62.3
spec:
  type: LoadBalancer
  selector:
    app: payara
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080
    - protocol: TCP
      name: https
      port: 443
      targetPort: 8181
    - protocol: TCP
      name: admin
      port: 4848
      targetPort: 4848
    - protocol: TCP
      name: debug
      port: 9009
      targetPort: 9009
    - protocol: TCP
      name: jmx-rmi
      port: 9010
      targetPort: 9010
    - protocol: TCP
      name: jmx-payara
      port: 8686
      targetPort: 8686
