apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: payara-applications
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi
