apiVersion: v1
kind: Service
metadata:
  name: payara
spec:
  type: LoadBalancer
  selector:
    app: payara
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080
    - protocol: TCP
      name: http1
      port: 8080
      targetPort: 8080
    - protocol: TCP
      name: https
      port: 443
      targetPort: 8181
    - protocol: TCP
      name: https1
      port: 8181
      targetPort: 8181
    - protocol: TCP
      name: admin
      port: 4848
      targetPort: 4848
