apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payara
  name: payara
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payara
  template:
    metadata:
      labels:
        app: payara
    spec:
      containers:
      - image: lprimak/payara-full
        name: server-full
---
apiVersion: v1
kind: Service
metadata:
  name: payara
  annotations:
#    metallb.universe.tf/loadBalancerIPs: 10.0.62.3
spec:
  type: LoadBalancer
  selector:
    app: payara
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080
    - protocol: TCP
      name: https
      port: 443
      targetPort: 8181
    - protocol: TCP
      name: admin
      port: 4848
      targetPort: 4848
