Vagrant.configure("2") do |config|
  config.vm.box = "flaszlo/oracle-9-arm64"

  config.vm.define "controller", primary: true do |controller|
    controller.vm.hostname = "controller"
    controller.vm.network "public_network",
        netmask: "255.255.0.0",
        ip: "10.0.13.1"
    config.vm.provider "vmware_desktop" do |v|
      v.vmx["memsize"] = "4096"
      v.vmx["numvcpus"] = "4"
    end
  end

  config.vm.define "node1" do |node1|
    node1.vm.network "public_network",
        netmask: "255.255.0.0",
        ip: "10.0.13.2"
    node1.vm.hostname = "node1"
  end

  config.vm.define "node2" do |node2|
    node2.vm.network "public_network",
        netmask: "255.255.0.0",
        ip: "10.0.13.3"
    node2.vm.hostname = "node2"
  end

  config.vm.provision "shell",
    run: "always",
    path: "provision.sh"
end
