symbol "DBL_SPAM" {
  score = 7.0;
}

symbol "BAD_REP_POLICIES" {
  score = 1.0;
}

symbol "HFILTER_HELO_IP_A" {
  score = 7.0;
}

symbol "RBL_SPAMHAUS_CSS" {
  score = 3.0;
}

symbol "RBL_SPAMHAUS_PBL" {
  score = 3.0;
}

symbol "ABUSE_SURBL" {
  score = 6.1;
}
