sender_whitelist = {
  type = "header";
  header = "from";
  filter = "email:domain";
  symbol = "SENDER_WHITELIST";
  map = "/etc/rspamd/local.d/whitelist_senders.map";
  score = -50.0;
  description = "Whitelisted sender";
}
