# Provisioning
compartment_id: "ocid1.tenancy.oc1..aaaaaaaajzdeabpe55pastcezhhjrqxopgyhvnjeqhi6hvjhvbeip7rl5e2a"
net_cidr_block: "10.0.0.0/24"
web_network_name: "web server network"
sec_network_name: "secure network"
web_host_name: "web1"
docker_host_name: 'containers'
web_test_host_name: "web test server"
docker_test_host_name: "containers test server"
web_availability_domain: "wjxn:US-CHICAGO-1-AD-2"
sec_availability_domain: "wjxn:US-CHICAGO-1-AD-3"
image_id: "ocid1.image.oc1.us-chicago-1.aaaaaaaaf5uzrnua5anuk3bxele3gqhi7szyt3hvkvvda4r5ytjbzzj7y7xq"

# Versions
k8s_version: 1.30
pause_container_version: 3.9
