- hosts: all:!localhost
  become: true
  vars:
    oci_hostname_conf_name: "/etc/oci-hostname.conf"
  tasks:
    - name: include vars
      include_vars: "{{ playbook_dir }}/config-vars.yaml"
      tags: always

    - name: Check for OCI hostname file
      stat:
        path: "{{ oci_hostname_conf_name }}"
      register: oci_hostname_conf

    - name: Ensure OCI doesn't clobber the hostname
      lineinfile:
        path: "{{ oci_hostname_conf_name }}"
        regexp: '^PRESERVE_HOSTINFO'
        line: 'PRESERVE_HOSTINFO=1'
      when: oci_hostname_conf.stat.exists

    - name: Set Hostname
      hostname:
        name: "{{ inventory_hostname_short }}"

    - name: Grow Filesystem
      command: /usr/libexec/oci-growfs -y
      changed_when: false
      when: oci_hostname_conf.stat.exists

    - name: Ensure yum-utils and firewalld is installed
      package:
        name:
          - yum-utils
          - firewalld
        state: present
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Disable Host Firewall
      service:
        name: firewalld
        state: stopped
        enabled: false

    - name: Set timezone
      timezone: "name={{ timezone }}"
