jenkins:
  authorizationStrategy:
    github:
      adminUserNames: "lprimak"
      allowAnonymousJobStatusPermission: false
      allowAnonymousReadPermission: true
      allowCcTrayPermission: false
      allowGithubWebHookPermission: true
      authenticatedUserCreateJobPermission: false
      authenticatedUserReadPermission: true
      organizationNames: "flowlogix"
      useRepositoryPermissions: false
  globalNodeProperties:
  - envVars:
      env:
      - key: "MAVEN_ADD_OPTIONS"
        value: "-Dwebdriver.browser=firefox"
  views:
  - all:
      name: "all"
  - calendar:
      includeRegex: ".*"
      name: "Build Timeline"
      recurse: true
  numExecutors: 0
  nodes:
    - permanent:
        launcher:
          inbound:
            webSocket: true
        name: "nova"
        nodeDescription: "Nova local agent"
        numExecutors: 4
        remoteFS: "hope-node"
        nodeProperties:
        - envVars:
            env:
              - key: "CHROME_BINARY"
                value: "^${HOME}/apps/google-chrome/97/Google Chrome.app/Contents/MacOS/Google Chrome"
              - key: "MAVEN_OPTS"
                value: "\
                \ -Dwebdriver.chrome.driver=^${HOME}/apps/chromedriver/97/chromedriver\
                \ -Dwebdriver.gecko.driver=^${HOMEBREW_PREFIX}/bin/geckodriver\
                \ -Dwebdriver.firefox.binary=^${HOME}/apps/firefox/120.0.1/Firefox.app/Contents/MacOS/firefox\
                \ "
    - permanent:
        launcher:
          inbound:
            webSocket: true
        name: "containers"
        labelString: "docker-agent"
        nodeDescription: "Docker Containers agent"
        numExecutors: 4
        remoteFS: "containers-node"
        mode: EXCLUSIVE
        nodeProperties:
          - envVars:
              env:
                - key: "MAVEN_OPTS"
                  value: "-Dwebdriver.gecko.driver=/usr/bin/geckodriver"
security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false
  scriptApproval:
    approvedSignatures:
    - "method io.jenkins.plugins.analysis.warnings.groovy.GroovyParser getId"
    - "method io.jenkins.plugins.analysis.warnings.groovy.ParserConfiguration getParsers"
    - "method io.jenkins.plugins.analysis.warnings.groovy.ParserConfiguration setParsers\
      \ java.util.List"
    - "new io.jenkins.plugins.analysis.warnings.groovy.GroovyParser java.lang.String\
      \ java.lang.String java.lang.String java.lang.String java.lang.String"
    - "staticMethod io.jenkins.plugins.analysis.warnings.groovy.ParserConfiguration\
      \ getInstance"
  queueItemAuthenticator:
    authenticators:
    - global:
        strategy: "triggeringUsersAuthorizationStrategy"
unclassified:
  gitHubPluginConfig:
    configs:
    - credentialsId: "1da457b5-282f-4dcd-8358-e1aaee34bbb3"
      name: "FlowLogix WebHook Auth"
    hookSecretConfigs:
    - credentialsId: "3cddf56f-7e59-4901-a779-b4326d2bb3c9"
  globalDefaultFlowDurabilityLevel:
    durabilityHint: PERFORMANCE_OPTIMIZED
  location:
    adminAddress: "admin@flowlogix.com"
    url: "https://jenkins.hope.nyc.ny.us/"
  mailer:
    defaultSuffix: "@flowlogix.com"
    smtpHost: "localhost"
  buildDiscarders:
    configuredBuildDiscarders:
    - simpleBuildDiscarder:
        discarder:
          logRotator:
            daysToKeepStr: "10"
            numToKeepStr: "10"
tool:
  pipelineMaven:
    daoClass: "org.jenkinsci.plugins.pipeline.maven.db.PipelineMavenPluginPostgreSqlDao"
    jdbcCredentialsId: "9e238cbe-c0cc-4221-a4fb-1d2d8dc5fe1c"
    jdbcUrl: "jdbc:postgresql://localhost:5432/hope"
    properties: "dataSource.sslmode=disable"
